name: Run tests and linters

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.12"
          - "3.13"
    env:
      UV_PYTHON: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Run tests with pytest
        run: uv run pytest --cov --cov-branch --cov-report=xml

      - name: Run mypy checker
        run: uv run mypy .

      - name: Run ruff linter
        run: uv run ruff check

      - name: Run ruff formatter
        run: uv run ruff format --check

      - name: Upload coverage reports to Codecov
        if: github.ref == 'refs/heads/main' && matrix.python-version == '3.13'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}


